### ISSUE TITLE
Cannot create pull request 

### ISSUE THREAD

**Issue by peter-gy** [uwdata/draco#109]
Hi,

I just addressed issues #106, #107 and #108 in my [fork](https://github.com/peter-gy/draco), however, I am not able to create a PR, since the corresponding button is disabled. Is this on purpose?

![Screenshot 2022-07-25 at 11 30 42](https://user-images.githubusercontent.com/40776291/180745581-ba55f408-d717-4c28-b4a7-479790bc47d9.png)

**Comment by domoritz** [comment]
Huh, weird. I can make a pull request and don't see a setting that's wrong. 

<img width="1257" alt="Screenshot 2022-07-27 at 11 46 44 AM" src="https://user-images.githubusercontent.com/589034/181291502-21e8b659-fa41-4535-9259-8f1936ac4392.png">

**Comment by peter-gy** [comment]
Thanks for checking on it. Weirdly, the `Create pull request` button was only disabled as I tried to merge my fork's `master` branch into this repo's `master`. As soon as I created a separate branch for the PR, I managed to open #110.
