### ISSUE TITLE
Pypi distribution should include asp / js files.

### ISSUE THREAD

**Issue by haldenl** [uwdata/draco#83]
Currently, we read asp / js files in the python package via `resolve('../{asp, js}')`. These directories were not included in the setup.py install (they are included in the distribution). Current band-aid fix here is adding `../asp`, `../js` to the `package_data` in setup.py, but this means they are installed outside of the `draco` package (e.g. looking in `site_packages` will give you `js` and `asp` directories in addition to the `draco` directory.

How should we remedy this?

**Comment by domoritz** [comment]
Hmm, if you use `setup.py develop`, you should get just a symlink and that should still work. So the issue is when you call `setup.py install`?

**Comment by haldenl** [comment]
yeah, i.e. via `pip install`.

**Comment by domoritz** [comment]
Oh, I guess just including the files (as you noted above) does not add the files to the installed package. Maybe we just need to follow https://python-packaging.readthedocs.io/en/latest/non-code-files.html.
