### ISSUE TITLE
sh run_pipeline.sh spec

### ISSUE THREAD

**Issue by 907929194** [uwdata/draco#89]
🌟 [OK] Start processing file spec...
usage: draco [-h] [--type {vl,asp}] [--mode {optimize,violations,valid}]
             [--out OUT] [--base BASE] [--debug] [--version]
             [query]
draco: error: argument query: can't open 'spec': [Errno 2] No such file or directory: 'spec'

**Comment by domoritz** [comment]
Please post the complete command you ran. What's the content of the spec/query you passed in?

**Comment by 907929194** [comment]
I want to run it with my own data，so I built the environment in VMvare according to the website “https://github.com/uwdata/draco”. An error has been encountered when I executed this sentencesh “run_pipeline.sh spec”, I don't know exactly what spec means. Thank you for your help.

**Comment by domoritz** [comment]
Replace spec with a partial specification such as https://github.com/uwdata/draco/blob/master/examples/scatter.vl.json.

**Comment by sjzryf** [comment]
sh run_pipeline.sh examples/scatter.vl.json
🌟 [OK] Start processing file examples/scatter.vl.json...
INFO:draco.cli:Processing query: examples/scatter.vl.json ...
ERROR:draco.run:b'-:1180:14-15: error: syntax error, unexpected :\n\n*** ERROR: (clingo): parsing failed\n'
ERROR:draco.run:Unsupported result: UNKNOWN
🌟 [OK] Output spec: __tmp__/scatter.vl.vl.json
run_pipeline.sh: 28: run_pipeline.sh: ./js/node_modules/.bin/vl2png: not found

**Comment by domoritz** [comment]
Looks like there is a syntax error in the generated ASP script. To fix the second issue, install Vega.

**Comment by sjzryf** [comment]
How to install Vega？Thanks！

**Comment by domoritz** [comment]
It's an npm package you install with `yarn add vega`. See https://vega.github.io/vega/usage/#cli.
