### ISSUE TITLE
Error in mypy test

### ISSUE THREAD

**Issue by GraceGSy** [uwdata/draco#90]
Hi there, I am getting an error when running the `mypy` tests.

![image](https://user-images.githubusercontent.com/16433058/74767235-790f5580-5254-11ea-8628-ccca4c2f3ccb.png)

All other tests passed, but I am not sure what went wrong for this one.

**Comment by domoritz** [comment]
@haldenl Do you know what's happening here?

**Comment by domoritz** [comment]
Fixed in https://github.com/uwdata/draco/commit/e58180d76c1fee844b7c1e4f9785ff68449d596a
