### ISSUE TITLE
A question about using wildcard encodings 

### ISSUE THREAD

**Issue by reflect9** [uwdata/draco#91]
Hello Draco developers, 

I really appreciate your time and efforts to create Draco.  I have a question about using Draco to replace CompassQl.   One of the main benefit of CompassQl is that users can assign wildcard (*) for channels - so that the model returns a large of number of charts with additional fields. Can I also do the same thing with Draco?  For the given documentation and examples, it seems that Draco does not allow wildcard.  Please forgive me (and delete this issue) if my question is completely dumb. 

best regards,
Tak

**Comment by domoritz** [comment]
Hi @reflect9. Welcome to Draco. I'm glad you find it useful. 

This is a great question and shows that you are deeply thinking about the recommendation. There is admittedly not much documentation in this repo so this question is totally valid. 

Yes, you can do the same in Draco. The semantics of Draco and CompassQL are slightly different in that Draco can assign a value to any property but soft constraints are used to not do it unless there is some other reason to do so. So in a way, Draco has wildcards for all properties already. Does that make sense?

**Comment by reflect9** [comment]
I see.  That makes sense!    

In the car example (https://uwdata.github.io/draco-editor/#/editor), all of them use only the two initial encodings (accelleration and horsepower).   But when I just added the third encoding without specifying which field should be mapped, it started showing more diverse charts. 

Thanks a lot!

**Comment by domoritz** [comment]
Adding a new encoding has really high cost so that's why you don't see any additional fields in the top-n recommendations.

**Comment by reflect9** [comment]
Thanks a lot for your answers!      The current soft constraints seem to prefer aggregates over additional fields.  It actually makes sense.    However, is there an easy way to control the cost of additional fields?   I think such control can let users choose the role of Draco as a design helper (i.e. finding the best setting with user-defined encodings) or data helper (i.e. showing a wide range of charts with additional fields).  


I am trying to adjust soft constraints to

**Comment by domoritz** [comment]
Yes, there is an easy way. You can pass in Constants to override weights via the clingo cli. Or you update the file with default weights.

**Comment by reflect9** [comment]
Thanks a lot!    I will try to play with those weights.

**Comment by reflect9** [comment]
I was wondering why Draco editor does not use additional fields other than horsepower and acceleration.  It seems that the "cars.json" data in the examples only contains two fields. Here are some of my experiments. 
-----
QUERY: encoding(e0).  encoding(e1).   
RESULT:  X:horsepower(binned);  Y:# records
-----
QUERY: encoding(e0).  encoding(e1).  :~ aggregate(e0,_). [1]  :~ aggregate(e1,_). [1] 
RESULT:  X:acceleration(binned);  Y:# records.    // the same result since the penalty (1) for using aggregation for the second encoding is small. 
-----
QUERY: encoding(e0).  encoding(e1).  :~ aggregate(e0,_). [2]  :~ aggregate(e1,_). [2] 
RESULT:  X:acceleration;  Y:horsepower.    // Now it shows non-aggregated fields for both encodings. 
-----

Thanks for your help.  I'd suggest the example dataset containing more fields. Also it would be super useful if there's an easy way to check the data schema.

**Comment by domoritz** [comment]
The data definition only has hp and acceleration so Draco only knows about them. 

```prolog
% ====== Data definitions ======
data("cars.json").
num_rows(142).

fieldtype(horsepower,number).
cardinality(horsepower,94).

fieldtype(acceleration,number).
cardinality(acceleration,96).

% ====== Query constraints ======
encoding(e0).
:- not field(e0,acceleration).

encoding(e1).
:- not field(e1,horsepower).
```

**Comment by reflect9** [comment]
Yes!  I just figured out.  Thanks a lot!
