### ISSUE TITLE
Build issues with Vega-Lite version and Rollup plugin

### ISSUE THREAD

**Issue by reflect9** [uwdata/draco#92]
If one clones the draco-core and call 'yarn build', he/she may have the same issue that I had as below.
`../node_modules/vega-lite/build/src/axis.d.ts:5:47 - error TS2315: Type 'BaseAxis' is not generic.`
and similar errors.     

I could fix it after I modified the Vega-Lite version in the packages.json from 3.2.1 to 4.10.2 - according to a Q&A about Vega-Lite compoliation issues (https://stackoverflow.com/questions/58388722/vega-charts-is-throwing-type-definition-error). 

I also had couple dependency issues of rollup and rollup-plugin-* modules, and could fix them by manually adding one by one using 'yarn add rollup' and so on.  

Thanks again for building this amazing library!

**Comment by domoritz** [comment]
The Vega typings version is fixed in https://github.com/uwdata/draco/blob/master/yarn.lock#L722 and so I think it would match? Things should work if you install deps with yarn.
